version: "3.4"

services:
  ioaksiteservice:
    image: ioaksiteservice
    container_name: ioaksiteservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      MINIO_URL: api.ioak.io
      MINIO_PORT: 8090
      MINIO_ACCESS_KEY: a2BSMeluIRysoTT6
      MINIO_SECRET: WoCjAVV0O4D8AzL3MWYmo2oR3NVWvora
      PORT: 8035
    ports:
      - 8035:8035
    networks:
      ioak-net:
        aliases:
          - ioaksiteservice.docker

networks:
  ioak-net:
    external: true
